### ISSUE TITLE
USER STORY: <As a User I can add new items so that I can keep stash up to date>

### ISSUE THREAD

**Issue by CozyPlantlady** [CozyPlantlady/yarn-guardian#9]
As a **User** I can **add new items** so that **I can keep stash up to date**.

- [x] App should have a form, that lets user add new items

- [x] Form should be in three stages:
Producer
Product name and details
Yarn color and amount.

- [x] If producer is already in the system, user should be able to find it.
- [x] If product is already in the system, user should be able to find it.
- [x] #83

- [x] #84
- [x] #85

- [x] Product name and details include The official name of the yarn, material(s), weight (how thick yarn is). 
- [x] #86

- [x] #54 
- [x] #55 
- [x] #57 
- [x] #20

**Comment by CozyPlantlady** [comment]
Form added.
